services:
  - type: web
    name: dcashier-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node simple-server.js
    repo: https://github.com/jimbon25/Dcashier-program
    branch: main
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    region: singapore
